### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by GoudronViande24** [XenKys/Ticketize#2]
You should add an open-source licence to your bot.
I recommend MIT licence.

**Comment by VoltDevelopment** [comment]
> You should add an open-source licence to your bot. I recommend MIT licence.

MIT is not the best licence unless you want people to profit out of your code

**Comment by GoudronViande24** [comment]
MIT is a great open-source license, it is used by many open-source projects.
Of course, there are many other license out there, and the choice has to be made by @XenKys.

**Comment by XenKys** [comment]
What license do you recommend to make sure people don't take advantage of my code?

**Comment by GoudronViande24** [comment]
AGPL would be a great license for that, it forces users to release the source code of any derivative work. It also requires people to keep the AGPL license for their adaptation.
Do you want me to make a PR with it added?

**Comment by XenKys** [comment]
Sorry for the ignorance but what is a PR?

**Comment by GoudronViande24** [comment]
[Pull Request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

**Comment by XenKys** [comment]
Oh, yes, I want

**Comment by GoudronViande24** [comment]
Just opened the PR here: #3.
To accept it, just press merge and close.

**Comment by GoudronViande24** [comment]
Why did you delete the license file right after?

**Comment by XenKys** [comment]
I made a mistake, can you redo the pr?

**Comment by GoudronViande24** [comment]
yeah no problem

**Comment by GoudronViande24** [comment]
Did it, see #4

**Comment by GoudronViande24** [comment]
Why have the license and readme been deleted again?
