### ISSUE TITLE
[HELP] With Installing

### ISSUE THREAD

**Issue by Bodeyibl** [XenKys/Ticketize#6]
hi, i got the ticket bot working afther many tries without knowing the ENV file. Now it turnes on and it says 
''D:\[Coding]\Desktop\Ticketize-main>node .      Connected to the database Mongo DB'' 
But i cant use a slash command or a prefix, is there any help? thanks in advance!
![image](https://user-images.githubusercontent.com/100451680/171056829-386c844c-470a-494d-9c84-a4930b936b89.png)

**Comment by XenKys** [comment]
Slash commands take a while to load, use client.guilds.cache.get("id").commands.set()

**Comment by Bodeyibl** [comment]
doesnt work, my bot only says "Connected to the database Mongo DB'', The bot it self is dead.

**Comment by XenKys** [comment]
Any errors?

**Comment by NotSoMik** [comment]
Just put your bot on and wait 2 hours
